<?php
$shopTitle = 'Adaptogens';
$shopProducts = [
    [
        'id' => '129688',
        'part_number' => 'SPN02364',
        'title' => 'California Gold Nutrition, Ashwagandha, 500 mg, 120 Veggie Capsules',
        'href' => 'pr/california-gold-nutrition-ashwagandha-500-mg-120-veggie-capsules/129688.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02364/u/120.jpg',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '4920.16',
        'list_price' => '4920.16',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '61634',
        'part_number' => 'CGN00949',
        'title' => 'California Gold Nutrition, Peruvian Maca, 500 mg, 90 Veggie Capsules',
        'href' => 'pr/california-gold-nutrition-peruvian-maca-500-mg-90-veggie-capsules/61634.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00949/u/138.jpg',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '1753.57',
        'list_price' => '1753.57',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '95838',
        'part_number' => 'NRB26876',
        'title' => 'NutraBio, KSM-66®, Ashwagandha , 90 Capsules',
        'href' => 'pr/nutrabio-ksm-66-ashwagandha-90-capsules/95838.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/nrb/nrb26876/u/48.jpg',
        'brand' => 'NutraBio',
        'discount_price' => '9714.73',
        'list_price' => '9714.73',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '114126',
        'part_number' => 'NCR90243',
        'title' => 'New Chapter, Magnesium + Ashwagandha, 60 Vegan Tablets',
        'href' => 'pr/new-chapter-magnesium-ashwagandha-60-vegan-tablets/114126.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncr/ncr90243/u/76.jpg',
        'brand' => 'New Chapter',
        'discount_price' => '8768.40',
        'list_price' => '8768.40',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '109031',
        'part_number' => 'SWV01957',
        'title' => 'Swanson Vitamins, Full Spectrum® Ashwagandha, 450 mg, 100 Vegan Capsules',
        'href' => 'pr/swanson-vitamins-full-spectrum-ashwagandha-450-mg-100-vegan-capsules/109031.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/swv/swv01957/u/97.jpg',
        'brand' => 'Swanson Vitamins',
        'discount_price' => '2444.12',
        'list_price' => '2444.12',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '16416',
        'part_number' => 'LEX88806',
        'title' => 'Life Extension, Optimized Ashwagandha, 60 Vegetarian Capsules (125 mg per Capsule)',
        'href' => 'pr/life-extension-optimized-ashwagandha-60-vegetarian-capsules-125-mg-per-capsule/16416.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lex/lex88806/u/117.jpg',
        'brand' => 'Life Extension',
        'discount_price' => '2784.77',
        'list_price' => '2784.77',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '104049',
        'part_number' => 'AGE00048',
        'title' => 'Codeage, Multi Collagen, 90 Vegetable Capsules',
        'href' => 'pr/codeage-multi-collagen-90-vegetable-capsules/104049.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/age/age00048/u/40.jpg',
        'brand' => 'Codeage',
        'discount_price' => '10114.94',
        'list_price' => '10114.94',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '87138',
        'part_number' => 'LEX16300',
        'title' => 'Life Extension, Adrenal Energy Formula, 120 Vegetarian Capsules',
        'href' => 'pr/life-extension-adrenal-energy-formula-120-vegetarian-capsules/87138.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lex/lex16300/u/68.jpg',
        'brand' => 'Life Extension',
        'discount_price' => '10471.95',
        'list_price' => '10471.95',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '310',
        'part_number' => 'NOW04603',
        'title' => 'NOW Foods, Ashwagandha, Standardized Extract, 450 mg, 90 Veg Capsules',
        'href' => 'pr/now-foods-ashwagandha-standardized-extract-450-mg-90-veg-capsules/310.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04603/u/83.jpg',
        'brand' => 'NOW Foods',
        'discount_price' => '3937.63',
        'list_price' => '3937.63',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '139433',
        'part_number' => 'NCS67927',
        'title' => 'Nutricost, KSM-66®, Ashwagandha Root Extract, 60 Capsules',
        'href' => 'pr/nutricost-ksm-66-ashwagandha-root-extract-60-capsules/139433.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67927/u/24.jpg',
        'brand' => 'Nutricost',
        'discount_price' => '4373.79',
        'list_price' => '4373.79',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '145913',
        'part_number' => 'NOW04633',
        'title' => 'NOW Foods, KSM-66 Ashwagandha®, 600 mg, 90 Veg Capsules',
        'href' => 'pr/now-foods-ksm-66-ashwagandha-600-mg-90-veg-capsules/145913.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04633/u/8.jpg',
        'brand' => 'NOW Foods',
        'discount_price' => '6427.77',
        'list_price' => '6427.77',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '78203',
        'part_number' => 'NOW04593',
        'title' => 'NOW Foods, Standardized Extract Ashwagandha, 450 mg, 180 Veg Capsules',
        'href' => 'pr/now-foods-standardized-extract-ashwagandha-450-mg-180-veg-capsules/78203.html',
        'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04593/u/27.jpg',
        'brand' => 'NOW Foods',
        'discount_price' => '6891.46',
        'list_price' => '6891.46',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '83135',
        'part_number' => 'HIM06043',
        'title' => 'Himalaya, Organic Ashwagandha, 90 Caplets',
        'href' => 'pr/himalaya-organic-ashwagandha-90-caplets/83135.html',
        'image' => '',
        'brand' => 'Himalaya',
        'discount_price' => '9163.47',
        'list_price' => '9163.47',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '128405',
        'part_number' => 'FOA66017',
        'title' => 'Force Factor, Fundamentals, Black Maca, 90 Capsules',
        'href' => 'pr/force-factor-fundamentals-black-maca-90-capsules/128405.html',
        'image' => '',
        'brand' => 'Force Factor',
        'discount_price' => '6237.09',
        'list_price' => '6237.09',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '9743',
        'part_number' => 'NOW04762',
        'title' => 'NOW Foods, Maca, 500 mg, 250 Veg Capsules',
        'href' => 'pr/now-foods-maca-500-mg-250-veg-capsules/9743.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '5198.02',
        'list_price' => '5198.02',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '113512',
        'part_number' => 'LEX25023',
        'title' => 'Life Extension, Rest & Renew, 30 Vegetarian Capsules',
        'href' => 'pr/life-extension-rest-renew-30-vegetarian-capsules/113512.html',
        'image' => '',
        'brand' => 'Life Extension',
        'discount_price' => '4097.72',
        'list_price' => '4097.72',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '18046',
        'part_number' => 'NOW04777',
        'title' => 'NOW Foods, Raw Maca, 750 mg, 90 Veg Capsules',
        'href' => 'pr/now-foods-raw-maca-750-mg-90-veg-capsules/18046.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '5321.17',
        'list_price' => '5321.17',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '4670',
        'part_number' => 'MRM71030',
        'title' => 'MRM Nutrition, Cordyceps CS-4 Strain, 60 Vegan Capsules (750 mg per Capsule)',
        'href' => 'pr/mrm-nutrition-cordyceps-cs-4-strain-60-vegan-capsules-750-mg-per-capsule/4670.html',
        'image' => '',
        'brand' => 'MRM Nutrition',
        'discount_price' => '4344.90',
        'list_price' => '4344.90',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '89863',
        'part_number' => 'CGN01365',
        'title' => 'California Gold Nutrition, Ashwagandha, 450 mg, 180 Veggie Capsules',
        'href' => 'pr/california-gold-nutrition-ashwagandha-450-mg-180-veggie-capsules/89863.html',
        'image' => '',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '6018.66',
        'list_price' => '6018.66',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '82697',
        'part_number' => 'CGN01218',
        'title' => 'California Gold Nutrition, Superfoods, Certified Organic Peruvian Maca Root Powder, 8.5 oz (240 g)',
        'href' => 'pr/california-gold-nutrition-superfoods-certified-organic-peruvian-maca-root-powder-8-5-oz-240-g/82697.html',
        'image' => '',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '2026.75',
        'list_price' => '2026.75',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '123306',
        'part_number' => 'NRB26875',
        'title' => 'NutraBio, KSM-66®, Ashwagandha, 60 Capsules (600 mg per Capsule)',
        'href' => 'pr/nutrabio-ksm-66-ashwagandha-60-capsules-600-mg-per-capsule/123306.html',
        'image' => '',
        'brand' => 'NutraBio',
        'discount_price' => '6948.73',
        'list_price' => '6948.73',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '3302',
        'part_number' => 'JRW22014',
        'title' => 'Jarrow Formulas, Ashwagandha, 300 mg, 120 Veggie Capsules',
        'href' => 'pr/jarrow-formulas-ashwagandha-300-mg-120-veggie-capsules/3302.html',
        'image' => '',
        'brand' => 'Jarrow Formulas',
        'discount_price' => '7079.24',
        'list_price' => '7079.24',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '69652',
        'part_number' => 'LEX18739',
        'title' => 'Life Extension, Bilberry Extract, 100 mg, 90 Vegetarian Capsules',
        'href' => 'pr/life-extension-bilberry-extract-100-mg-90-vegetarian-capsules/69652.html',
        'image' => '',
        'brand' => 'Life Extension',
        'discount_price' => '9614.83',
        'list_price' => '9614.83',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '78505',
        'part_number' => 'ALG71810',
        'title' => 'Allergy Research Group, Thyroid, 40 mg, 100 Vegetarian Capsules',
        'href' => 'pr/allergy-research-group-thyroid-40-mg-100-vegetarian-capsules/78505.html',
        'image' => '',
        'brand' => 'Allergy Research Group',
        'discount_price' => '10114.94',
        'list_price' => '10114.94',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '5253',
        'part_number' => 'NTA00640',
        'title' => 'Nature\'s Answer, Licorice Root Fluid Extract, Alcohol-Free, 2,000 mg, 1 fl oz (30 ml)',
        'href' => 'pr/nature-s-answer-licorice-root-fluid-extract-alcohol-free-2-000-mg-1-fl-oz-30-ml/5253.html',
        'image' => '',
        'brand' => 'Nature&#x27;s Answer',
        'discount_price' => '3268.86',
        'list_price' => '3268.86',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '104633',
        'part_number' => 'GOI35740',
        'title' => 'Goli Nutrition, Ashwagandha Gummies, 60 Gummies',
        'href' => 'pr/goli-nutrition-ashwagandha-gummies-60-gummies/104633.html',
        'image' => '',
        'brand' => 'Goli Nutrition',
        'discount_price' => '5314.46',
        'list_price' => '5314.46',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '81243',
        'part_number' => 'NOW04654',
        'title' => 'NOW Foods, DGL with Aloe Vera, 400 mg, 100 Veg Capsules',
        'href' => 'pr/now-foods-dgl-with-aloe-vera-400-mg-100-veg-capsules/81243.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '3937.63',
        'list_price' => '3937.63',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '112602',
        'part_number' => 'AGE00856',
        'title' => 'Codeage, Meditate Vitamins+, 60 Capsules',
        'href' => 'pr/codeage-meditate-vitamins-60-capsules/112602.html',
        'image' => '',
        'brand' => 'Codeage',
        'discount_price' => '10982.18',
        'list_price' => '10982.18',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '104480',
        'part_number' => 'FOA01488',
        'title' => 'Force Factor, Fundamentals, Black Maca, 60 Capsules',
        'href' => 'pr/force-factor-fundamentals-black-maca-60-capsules/104480.html',
        'image' => '',
        'brand' => 'Force Factor',
        'discount_price' => '4173.17',
        'list_price' => '4173.17',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '2626',
        'part_number' => 'NFS04508',
        'title' => 'Natural Factors, DGL, Deglycyrrhizinated Licorice Root Extract, 90 Chewable Tablets',
        'href' => 'pr/natural-factors-dgl-deglycyrrhizinated-licorice-root-extract-90-chewable-tablets/2626.html',
        'image' => '',
        'brand' => 'Natural Factors',
        'discount_price' => '3636.17',
        'list_price' => '3636.17',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '147960',
        'part_number' => 'LMM54902',
        'title' => 'Lemme, Chill, Ashwagandha Gummies, Mixed Berry, 60 Gummies',
        'href' => 'pr/lemme-chill-ashwagandha-gummies-mixed-berry-60-gummies/147960.html',
        'image' => '',
        'brand' => 'Lemme',
        'discount_price' => '9286.43',
        'list_price' => '9286.43',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '139648',
        'part_number' => 'NCA63913',
        'title' => 'Nature\'s Craft, Organic Ashwagandha, 30 ml',
        'href' => 'pr/nature-s-craft-organic-ashwagandha-30-ml/139648.html',
        'image' => '',
        'brand' => 'Nature&#x27;s Craft',
        'discount_price' => '4511.56',
        'list_price' => '4511.56',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '105928',
        'part_number' => 'NFS04507',
        'title' => 'Natural Factors, DGL, Deglycyrrhizinated Licorice Root Extract, 180 Chewable Tablets',
        'href' => 'pr/natural-factors-dgl-deglycyrrhizinated-licorice-root-extract-180-chewable-tablets/105928.html',
        'image' => '',
        'brand' => 'Natural Factors',
        'discount_price' => '6165.52',
        'list_price' => '6165.52',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '117559',
        'part_number' => 'SWV11004',
        'title' => 'Swanson Vitamins, Full Spectrum® Rhodiola Rosea Root, 400 mg, 100 Vegan Capsules',
        'href' => 'pr/swanson-vitamins-full-spectrum-rhodiola-rosea-root-400-mg-100-vegan-capsules/117559.html',
        'image' => '',
        'brand' => 'Swanson Vitamins',
        'discount_price' => '3170.29',
        'list_price' => '3170.29',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '90165',
        'part_number' => 'YOU00758',
        'title' => 'Youtheory, Ashwagandha, 60 Vegetarian Capsules',
        'href' => 'pr/youtheory-ashwagandha-60-vegetarian-capsules/90165.html',
        'image' => '',
        'brand' => 'Youtheory',
        'discount_price' => '5300.67',
        'list_price' => '5300.67',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '68252',
        'part_number' => 'SBL00129',
        'title' => 'Sambucol, Black Elderberry, Effervescent Tablets + Vitamin C & Zinc, Age 4+, 15 Effervescent Tablets',
        'href' => 'pr/sambucol-black-elderberry-effervescent-tablets-vitamin-c-zinc-age-4-15-effervescent-tablets/68252.html',
        'image' => '',
        'brand' => 'Sambucol',
        'discount_price' => '2855.66',
        'list_price' => '2855.66',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '82849',
        'part_number' => 'CGN01256',
        'title' => 'California Gold Nutrition, Reishi (Ganoderma lucidum), Full Spectrum, Certified Organic, 90 Veggie Capsules (600 mg Per Veggie Capsule)',
        'href' => 'pr/california-gold-nutrition-reishi-ganoderma-lucidum-full-spectrum-certified-organic-90-veggie-capsules-600-mg-per-veggie-capsule/82849.html',
        'image' => '',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '3018.00',
        'list_price' => '3018.00',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '117596',
        'part_number' => 'SWV11136',
        'title' => 'Swanson Vitamins, Full Spectrum® Korean Red Ginseng Root, 400 mg, 90 Capsules',
        'href' => 'pr/swanson-vitamins-full-spectrum-korean-red-ginseng-root-400-mg-90-capsules/117596.html',
        'image' => '',
        'brand' => 'Swanson Vitamins',
        'discount_price' => '2524.02',
        'list_price' => '2524.02',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '336',
        'part_number' => 'NOW04721',
        'title' => 'NOW Foods, Maca, 500 mg, 100 Veg Capsules',
        'href' => 'pr/now-foods-maca-500-mg-100-veg-capsules/336.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '2796.34',
        'list_price' => '2796.34',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '123463',
        'part_number' => 'NOW04767',
        'title' => 'NOW Foods, Rhodiola, 500 mg , 120 Veg Capsules',
        'href' => 'pr/now-foods-rhodiola-500-mg-120-veg-capsules/123463.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '9678.77',
        'list_price' => '9678.77',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '140223',
        'part_number' => 'NCS57213',
        'title' => 'Nutricost, Ashwagandha Root Extract, 600 mg, 120 Capsules',
        'href' => 'pr/nutricost-ashwagandha-root-extract-600-mg-120-capsules/140223.html',
        'image' => '',
        'brand' => 'Nutricost',
        'discount_price' => '4436.23',
        'list_price' => '4436.23',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '102553',
        'part_number' => 'CGN01883',
        'title' => 'California Gold Nutrition, Total C Complex with Ascorbic Acid, Amla Extract, Citrus Bioflavonoids & Rose Hip Extract, 500 mg, 60 Veggie Capsules',
        'href' => 'pr/california-gold-nutrition-total-c-complex-with-ascorbic-acid-amla-extract-citrus-bioflavonoids-rose-hip-extract-500-mg-60-veggie-capsules/102553.html',
        'image' => '',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '1545.43',
        'list_price' => '1545.43',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '111020',
        'part_number' => 'SWV02990',
        'title' => 'Swanson Vitamins, Lutein & Bilberry, 120 Softgels',
        'href' => 'pr/swanson-vitamins-lutein-bilberry-120-softgels/111020.html',
        'image' => '',
        'brand' => 'Swanson Vitamins',
        'discount_price' => '3896.46',
        'list_price' => '3896.46',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '27019',
        'part_number' => 'NOW03005',
        'title' => 'NOW Foods, Cordyceps, 90 Veg Capsules (750 mg per Capsule)',
        'href' => 'pr/now-foods-cordyceps-90-veg-capsules-750-mg-per-capsule/27019.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '5513.46',
        'list_price' => '5513.46',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '82850',
        'part_number' => 'CGN01258',
        'title' => 'California Gold Nutrition, Fungiology, MushRex Plus, Full-Spectrum Ten Mushroom Complex with Agaricus, Chaga, Cordyceps, and Lion\'s Mane, 120 Plantcaps',
        'href' => 'pr/california-gold-nutrition-fungiology-mushrex-plus-full-spectrum-ten-mushroom-complex-with-agaricus-chaga-cordyceps-and-lion-s-mane-120-plantcaps/82850.html',
        'image' => '',
        'brand' => 'California Gold Nutrition',
        'discount_price' => '4334.47',
        'list_price' => '4334.47',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '335',
        'part_number' => 'NOW04754',
        'title' => 'NOW Foods, Rhodiola, 500 mg, 60 Veg Capsules',
        'href' => 'pr/now-foods-rhodiola-500-mg-60-veg-capsules/335.html',
        'image' => '',
        'brand' => 'NOW Foods',
        'discount_price' => '7136.60',
        'list_price' => '7136.60',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
    [
        'id' => '67039',
        'part_number' => 'LEX20043',
        'title' => 'Life Extension, Arterial Protect, 30 Vegetarian Capsules',
        'href' => 'pr/life-extension-arterial-protect-30-vegetarian-capsules/67039.html',
        'image' => '',
        'brand' => 'Life Extension',
        'discount_price' => '11156.21',
        'list_price' => '11156.21',
        'rating_count' => '',
        'review_href' => '',
        'rating_title' => '',
    ],
];
?>
