<?php
$trendingCategories = [
    [
        'title' => 'Trending now',
        'view_all' => 'index881d.html?type=0',
        'products' => [
            [
                'id' => '111467',
                'part_number' => 'SPN02140',
                'title' => 'California Gold Nutrition, Omega-3 Fish Oil, Vivomega Triglyceride, 1,000 mg, 90 Fish Gelatin Softgels',
                'href' => 'pr/california-gold-nutrition-omega-3-fish-oil-vivomega-triglyceride-1-000-mg-90-fish-gelatin-softgels/111467.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02140/r/58.jpg',
                'brand' => 'CGN',
                'discount_price' => '5042.14',
                'list_price' => '6722.86',
                'discount_percent' => '25',
                'rating_title' => '4.8/5 - 11,517 Reviews',
                'rating_count' => '11,517',
                'review_href' => 'r/california-gold-nutrition-omega-3-fish-oil-vivomega-triglyceride-1-000-mg-90-fish-gelatin-softgels/111467.html',
            ],
            [
                'id' => '138418',
                'part_number' => 'SRE09167',
                'title' => 'Sports Research, Alaskan Omega-3 Fish Oil, Mini Gels, 120 Softgels',
                'href' => 'pr/sports-research-alaskan-omega-3-fish-oil-mini-gels-120-softgels/138418.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/sre/sre09167/r/28.jpg',
                'brand' => 'SRE',
                'discount_price' => '9028.69',
                'list_price' => '9028.69',
                'discount_percent' => '0',
                'rating_title' => '4.9/5 - 1,503 Reviews',
                'rating_count' => '1,503',
                'review_href' => 'r/sports-research-alaskan-omega-3-fish-oil-mini-gels-120-softgels/138418.html',
            ],
            [
                'id' => '121505',
                'part_number' => 'NOW07881',
                'title' => 'NOW Foods, Solutions, Collagen Jelly Beauty Complex, Sweet Plum, 10 Jelly Sticks, 0.705 oz (20 g) Each',
                'href' => 'pr/now-foods-solutions-collagen-jelly-beauty-complex-sweet-plum-10-jelly-sticks-0-705-oz-20-g-each/121505.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now07881/r/43.jpg',
                'brand' => 'NOW',
                'discount_price' => '4145.77',
                'list_price' => '4145.77',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 600 Reviews',
                'rating_count' => '600',
                'review_href' => 'r/now-foods-solutions-collagen-jelly-beauty-complex-sweet-plum-10-jelly-sticks-0-705-oz-20-g-each/121505.html',
            ],
            [
                'id' => '108205',
                'part_number' => 'LRG00046',
                'title' => 'Lundberg, Organic Thin Brown Rice Cakes, Lightly Salted, 6 oz (168 g)',
                'href' => 'pr/lundberg-organic-thin-brown-rice-cakes-lightly-salted-6-oz-168-g/108205.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/lrg/lrg00046/r/32.jpg',
                'brand' => 'LRG',
                'discount_price' => '1741.03',
                'list_price' => '1741.03',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 580 Reviews',
                'rating_count' => '580',
                'review_href' => 'r/lundberg-organic-thin-brown-rice-cakes-lightly-salted-6-oz-168-g/108205.html',
            ],
            [
                'id' => '46873',
                'part_number' => 'DRB00230',
                'title' => 'Doctor\'s Best, Curcumin Phytosome™, 180 Veggie Caps (500 mg per Capsule)',
                'href' => 'pr/doctor-s-best-curcumin-phytosome-180-veggie-caps-500-mg-per-capsule/46873.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/drb/drb00230/r/156.jpg',
                'brand' => 'DRB',
                'discount_price' => '17637.05',
                'list_price' => '17637.05',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 6,839 Reviews',
                'rating_count' => '6,839',
                'review_href' => 'r/doctor-s-best-curcumin-phytosome-180-veggie-caps-500-mg-per-capsule/46873.html',
            ],
            [
                'id' => '38731',
                'part_number' => 'THB10016',
                'title' => 'TheraBreath, Fresh Breath, Oral Rinse, Mild Mint, 16 fl oz (473 ml)',
                'href' => 'pr/therabreath-fresh-breath-oral-rinse-mild-mint-16-fl-oz-473-ml/38731.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/thb/thb10016/r/51.jpg',
                'brand' => 'THB',
                'discount_price' => '3767.19',
                'list_price' => '3767.19',
                'discount_percent' => '0',
                'rating_title' => '4.6/5 - 45,411 Reviews',
                'rating_count' => '45,411',
                'review_href' => 'r/therabreath-fresh-breath-oral-rinse-mild-mint-16-fl-oz-473-ml/38731.html',
            ],
            [
                'id' => '89565',
                'part_number' => 'EBY00039',
                'title' => 'Embryolisse, Multi-Function Moisturizer, 1.01 fl oz (30 ml)',
                'href' => 'pr/embryolisse-multi-function-moisturizer-1-01-fl-oz-30-ml/89565.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/eby/eby00039/r/42.jpg',
                'brand' => 'EBY',
                'discount_price' => '2009.11',
                'list_price' => '5232.36',
                'discount_percent' => '62',
                'rating_title' => '4.6/5 - 11,444 Reviews',
                'rating_count' => '11,444',
                'review_href' => 'r/embryolisse-multi-function-moisturizer-1-01-fl-oz-30-ml/89565.html',
            ],
        ],
    ],
    [
        'title' => 'Best in Supplements',
        'view_all' => 'index881d.html?type=0',
        'products' => [
            [
                'id' => '72316',
                'part_number' => 'CGN01129',
                'title' => 'California Gold Nutrition, Sport, L-Citrulline, Kyowa Hakko, 500 mg, 60 Veggie Capsules',
                'href' => 'pr/california-gold-nutrition-sport-l-citrulline-kyowa-hakko-500-mg-60-veggie-capsules/72316.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01129/r/136.jpg',
                'brand' => 'CGN',
                'discount_price' => '2081.38',
                'list_price' => '2081.38',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 3,750 Reviews',
                'rating_count' => '3,750',
                'review_href' => 'r/california-gold-nutrition-sport-l-citrulline-kyowa-hakko-500-mg-60-veggie-capsules/72316.html',
            ],
            [
                'id' => '34645',
                'part_number' => 'WLD00080',
                'title' => 'Wild Planet, Wild Sardines In Extra Virgin Olive Oil, Lightly Smoked, 4.4 oz (125 g)',
                'href' => 'pr/wild-planet-wild-sardines-in-extra-virgin-olive-oil-lightly-smoked-4-4-oz-125-g/34645.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/wld/wld00080/r/63.jpg',
                'brand' => 'WLD',
                'discount_price' => '1185.46',
                'list_price' => '1185.46',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 3,303 Reviews',
                'rating_count' => '3,303',
                'review_href' => 'r/wild-planet-wild-sardines-in-extra-virgin-olive-oil-lightly-smoked-4-4-oz-125-g/34645.html',
            ],
            [
                'id' => '32029',
                'part_number' => 'GBR04830',
                'title' => 'Gerber, Snacks for Baby, Lil\' Crunchies®, Baked Grain Snack, 8+ Months, Mild Cheddar, 1.48 oz (42 g)',
                'href' => 'pr/gerber-snacks-for-baby-lil-crunchies-baked-grain-snack-8-months-mild-cheddar-1-48-oz-42-g/32029.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/gbr/gbr04830/r/44.jpg',
                'brand' => 'GBR',
                'discount_price' => '1447.00',
                'list_price' => '1447.00',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 6,934 Reviews',
                'rating_count' => '6,934',
                'review_href' => 'r/gerber-snacks-for-baby-lil-crunchies-baked-grain-snack-8-months-mild-cheddar-1-48-oz-42-g/32029.html',
            ],
            [
                'id' => '111472',
                'part_number' => 'MBE02148',
                'title' => 'California Gold Nutrition, Sleep Time Balm Stick, Lavender & Chamomile, 0.6 oz (17 g)',
                'href' => 'pr/california-gold-nutrition-sleep-time-balm-stick-lavender-chamomile-0-6-oz-17-g/111472.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mbe/mbe02148/r/67.jpg',
                'brand' => 'CGN',
                'discount_price' => '636.55',
                'list_price' => '1273.11',
                'discount_percent' => '50',
                'rating_title' => '4.5/5 - 10,880 Reviews',
                'rating_count' => '10,880',
                'review_href' => 'r/california-gold-nutrition-sleep-time-balm-stick-lavender-chamomile-0-6-oz-17-g/111472.html',
            ],
            [
                'id' => '113008',
                'part_number' => 'NOW00486',
                'title' => 'NOW Foods, Pantothenic Acid, 500 mg, 100 Veg Capsules',
                'href' => 'pr/now-foods-pantothenic-acid-500-mg-100-veg-capsules/113008.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00486/r/38.jpg',
                'brand' => 'NOW',
                'discount_price' => '2820.62',
                'list_price' => '2820.62',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 11,871 Reviews',
                'rating_count' => '11,871',
                'review_href' => 'r/now-foods-pantothenic-acid-500-mg-100-veg-capsules/113008.html',
            ],
            [
                'id' => '147495',
                'part_number' => 'CGN02548',
                'title' => 'California Gold Nutrition, Strengthening Hair & Scalp Oil, Biotin, Rosemary Mint, 2 fl oz (59 ml)',
                'href' => 'pr/california-gold-nutrition-strengthening-hair-scalp-oil-biotin-rosemary-mint-2-fl-oz-59-ml/147495.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn02548/r/9.jpg',
                'brand' => 'CGN',
                'discount_price' => '1445.40',
                'list_price' => '2890.81',
                'discount_percent' => '50',
                'rating_title' => '4.6/5 - 1,123 Reviews',
                'rating_count' => '1,123',
                'review_href' => 'r/california-gold-nutrition-strengthening-hair-scalp-oil-biotin-rosemary-mint-2-fl-oz-59-ml/147495.html',
            ],
            [
                'id' => '82854',
                'part_number' => 'MBN01262',
                'title' => 'Mild By Nature, Camellia Care®, Green Tea Skin Cream, 1.7 fl oz (50 ml)',
                'href' => 'pr/mild-by-nature-camellia-care-green-tea-skin-cream-1-7-fl-oz-50-ml/82854.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mbn/mbn01262/r/138.jpg',
                'brand' => 'MBN',
                'discount_price' => '1824.68',
                'list_price' => '3649.36',
                'discount_percent' => '50',
                'rating_title' => '4.6/5 - 25,689 Reviews',
                'rating_count' => '25,689',
                'review_href' => 'r/mild-by-nature-camellia-care-green-tea-skin-cream-1-7-fl-oz-50-ml/82854.html',
            ],
        ],
    ],
    [
        'title' => 'Sports & Fitness Picks',
        'view_all' => 'index881d.html?type=0',
        'products' => [
            [
                'id' => '143326',
                'part_number' => 'CGN02520',
                'title' => 'California Gold Nutrition, Ubiquinol Reduced Form CoQ10 + PQQ, 120 Veggie Capsules',
                'href' => 'pr/california-gold-nutrition-ubiquinol-reduced-form-coq10-pqq-120-veggie-capsules/143326.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn02520/r/114.jpg',
                'brand' => 'CGN',
                'discount_price' => '11988.76',
                'list_price' => '11988.76',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 953 Reviews',
                'rating_count' => '953',
                'review_href' => 'r/california-gold-nutrition-ubiquinol-reduced-form-coq10-pqq-120-veggie-capsules/143326.html',
            ],
            [
                'id' => '120467',
                'part_number' => 'TNN31111',
                'title' => 'Tru Niagen, Nicotinamide Riboside Chloride, 300 mg, 30 Vegetarian Capsules',
                'href' => 'pr/tru-niagen-nicotinamide-riboside-chloride-300-mg-30-vegetarian-capsules/120467.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/tnn/tnn31111/r/32.jpg',
                'brand' => 'TNN',
                'discount_price' => '11563.23',
                'list_price' => '11563.23',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 2,459 Reviews',
                'rating_count' => '2,459',
                'review_href' => 'r/tru-niagen-nicotinamide-riboside-chloride-300-mg-30-vegetarian-capsules/120467.html',
            ],
            [
                'id' => '100112',
                'part_number' => 'SEV44653',
                'title' => 'Seventh Generation, Power+, Laundry Spray Stain Remover, Fragrance Free, 16 fl oz (473 ml)',
                'href' => 'pr/seventh-generation-power-laundry-spray-stain-remover-fragrance-free-16-fl-oz-473-ml/100112.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/sev/sev44653/r/28.jpg',
                'brand' => 'SEV',
                'discount_price' => '2306.86',
                'list_price' => '2306.86',
                'discount_percent' => '0',
                'rating_title' => '4.5/5 - 1,707 Reviews',
                'rating_count' => '1,707',
                'review_href' => 'r/seventh-generation-power-laundry-spray-stain-remover-fragrance-free-16-fl-oz-473-ml/100112.html',
            ],
            [
                'id' => '498',
                'part_number' => 'NOW02645',
                'title' => 'NOW Foods, Chlorophyll, 90 Capsules',
                'href' => 'pr/now-foods-chlorophyll-90-capsules/498.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now02645/r/62.jpg',
                'brand' => 'NOW',
                'discount_price' => '4663.80',
                'list_price' => '4663.80',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 23,313 Reviews',
                'rating_count' => '23,313',
                'review_href' => 'r/now-foods-chlorophyll-90-capsules/498.html',
            ],
            [
                'id' => '96246',
                'part_number' => 'CGN01470',
                'title' => 'California Gold Nutrition, Glucosamine, Chondroitin, MSM plus Hyaluronic Acid, 60 Veggie Capsules',
                'href' => 'pr/california-gold-nutrition-glucosamine-chondroitin-msm-plus-hyaluronic-acid-60-veggie-capsules/96246.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01470/r/74.jpg',
                'brand' => 'CGN',
                'discount_price' => '3115.13',
                'list_price' => '3115.13',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 23,130 Reviews',
                'rating_count' => '23,130',
                'review_href' => 'r/california-gold-nutrition-glucosamine-chondroitin-msm-plus-hyaluronic-acid-60-veggie-capsules/96246.html',
            ],
            [
                'id' => '135520',
                'part_number' => 'NCS67336',
                'title' => 'Nutricost, Lithium Orotate, 5 mg, 120 Capsules',
                'href' => 'pr/nutricost-lithium-orotate-5-mg-120-capsules/135520.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ncs/ncs67336/r/25.jpg',
                'brand' => 'NCS',
                'discount_price' => '3834.37',
                'list_price' => '3834.37',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 577 Reviews',
                'rating_count' => '577',
                'review_href' => 'r/nutricost-lithium-orotate-5-mg-120-capsules/135520.html',
            ],
            [
                'id' => '6108',
                'part_number' => 'NOW00364',
                'title' => 'NOW Foods, Vitamin D-3, 400 IU, 180 Softgels',
                'href' => 'pr/now-foods-vitamin-d-3-400-iu-180-softgels/6108.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now00364/r/53.jpg',
                'brand' => 'NOW',
                'discount_price' => '1620.36',
                'list_price' => '1620.36',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 4,956 Reviews',
                'rating_count' => '4,956',
                'review_href' => 'r/now-foods-vitamin-d-3-400-iu-180-softgels/6108.html',
            ],
        ],
    ],
    [
        'title' => 'Beauty & Personal Care',
        'view_all' => 'index881d.html?type=0',
        'products' => [
            [
                'id' => '592',
                'part_number' => 'NOW04680',
                'title' => 'NOW Foods, Ginger Root, 550 mg, 100 Veg Capsules',
                'href' => 'pr/now-foods-ginger-root-550-mg-100-veg-capsules/592.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now04680/r/52.jpg',
                'brand' => 'NOW',
                'discount_price' => '2415.91',
                'list_price' => '2415.91',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 3,560 Reviews',
                'rating_count' => '3,560',
                'review_href' => 'r/now-foods-ginger-root-550-mg-100-veg-capsules/592.html',
            ],
            [
                'id' => '90196',
                'part_number' => 'IMF07476',
                'title' => 'I\'m From, Rice Toner, 5.07 fl oz (150 ml)',
                'href' => 'pr/i-m-from-rice-toner-5-07-fl-oz-150-ml/90196.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/imf/imf07476/r/69.jpg',
                'brand' => 'IMF',
                'discount_price' => '7870.51',
                'list_price' => '7870.51',
                'discount_percent' => '0',
                'rating_title' => '4.7/5 - 6,982 Reviews',
                'rating_count' => '6,982',
                'review_href' => 'r/i-m-from-rice-toner-5-07-fl-oz-150-ml/90196.html',
            ],
            [
                'id' => '115990',
                'part_number' => 'HEI76200',
                'title' => 'Heimish, Dailism, Smudge Stop Mascara, Volume, Black, 0.31 oz (9 g)',
                'href' => 'pr/heimish-dailism-smudge-stop-mascara-volume-black-0-31-oz-9-g/115990.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/hei/hei76200/r/92.jpg',
                'brand' => 'HEI',
                'discount_price' => '2986.78',
                'list_price' => '2986.78',
                'discount_percent' => '0',
                'rating_title' => '4.6/5 - 4,753 Reviews',
                'rating_count' => '4,753',
                'review_href' => 'r/heimish-dailism-smudge-stop-mascara-volume-black-0-31-oz-9-g/115990.html',
            ],
            [
                'id' => '129685',
                'part_number' => 'SPN02357',
                'title' => 'California Gold Nutrition, Magnesium Glycinate, 180 Veggie Capsules (133 mg per Capsule)',
                'href' => 'pr/california-gold-nutrition-magnesium-glycinate-180-veggie-capsules-133-mg-per-capsule/129685.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02357/r/30.jpg',
                'brand' => 'CGN',
                'discount_price' => '7628.26',
                'list_price' => '7628.26',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 2,774 Reviews',
                'rating_count' => '2,774',
                'review_href' => 'r/california-gold-nutrition-magnesium-glycinate-180-veggie-capsules-133-mg-per-capsule/129685.html',
            ],
            [
                'id' => '719',
                'part_number' => 'NOW03021',
                'title' => 'NOW Foods, Phase 2®, Starch Neutralizer, 500 mg, 120 Veg Capsules',
                'href' => 'pr/now-foods-phase-2-starch-neutralizer-500-mg-120-veg-capsules/719.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/now/now03021/r/55.jpg',
                'brand' => 'NOW',
                'discount_price' => '6825.55',
                'list_price' => '6825.55',
                'discount_percent' => '0',
                'rating_title' => '4.5/5 - 4,227 Reviews',
                'rating_count' => '4,227',
                'review_href' => 'r/now-foods-phase-2-starch-neutralizer-500-mg-120-veg-capsules/719.html',
            ],
            [
                'id' => '115180',
                'part_number' => 'AML00019',
                'title' => 'AmLactin, Daily Nourish Lotion, Normal to Dry Skin, 14.1 oz (400 g)',
                'href' => 'pr/amlactin-daily-nourish-lotion-normal-to-dry-skin-14-1-oz-400-g/115180.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/aml/aml00019/r/28.jpg',
                'brand' => 'AML',
                'discount_price' => '7124.57',
                'list_price' => '7124.57',
                'discount_percent' => '0',
                'rating_title' => '4.5/5 - 5,887 Reviews',
                'rating_count' => '5,887',
                'review_href' => 'r/amlactin-daily-nourish-lotion-normal-to-dry-skin-14-1-oz-400-g/115180.html',
            ],
            [
                'id' => '92368',
                'part_number' => 'SRE01256',
                'title' => 'Sports Research, Astaxanthin, Triple Strength, 12 mg, 60 Softgels',
                'href' => 'pr/sports-research-astaxanthin-triple-strength-12-mg-60-softgels/92368.html',
                'image' => 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/sre/sre01256/r/118.jpg',
                'brand' => 'SRE',
                'discount_price' => '9603.96',
                'list_price' => '9603.96',
                'discount_percent' => '0',
                'rating_title' => '4.8/5 - 4,847 Reviews',
                'rating_count' => '4,847',
                'review_href' => 'r/sports-research-astaxanthin-triple-strength-12-mg-60-softgels/92368.html',
            ],
        ],
    ],
];
?>
